Simple todos graphql
meteor/react-tutorial pull request #28
Opened 2021-04-22 21:47 UTC by denihs

New tutorial showing how to use GraphQL with Meteor.

2021-04-29 10:09 UTC, StorytellerCZ requested changes

2021-04-29 10:09 UTC, StorytellerCZ commented on _config.yml
> +    - simple-todos-graphql/02-especific-data
`especific` typo?

2021-04-29 10:09 UTC, StorytellerCZ commented on src/simple-todos-graphql/step01/.meteor/release
> +METEOR@2.0
Best to upgrade to the latest version.

2021-04-29 10:09 UTC, StorytellerCZ commented on src/simple-todos-graphql/step01/client/main.jsx
> +import { startGraphQLClient } from 'meteor/quave:graphql/client';
As much as `quave:graphql` is fine, I think we should stick to the official one via skeleton.

2021-05-04 18:51 UTC, filipenevola commented on _config.yml
> +    - simple-todos-graphql/02-especific-data
fixed

2021-05-04 18:52 UTC, filipenevola approved these changes

2021-05-04 19:48 UTC, merged