Update 01-creating-app.md
meteor/react-tutorial pull request #5
Opened 2020-09-18 16:18 UTC by MattH1611

2020-09-18 17:06 UTC, filipenevola requested changes

2020-09-18 17:06 UTC, filipenevola commented on tutorial/simple-todos/01-creating-app.md
> +In the next section we are going to work with our MongoDB database to store our tasks.
@MattH1611 each number is called step.

2020-09-18 17:10 UTC, MattH1611 reviewed
Changed that to Step.

2020-09-18 17:10 UTC, MattH1611 commented on tutorial/simple-todos/01-creating-app.md
> +In the next section we are going to work with our MongoDB database to store our tasks.
```suggestion
In the next step we are going to work with our MongoDB database to store our tasks.
```

2020-10-01 10:03 UTC, filipenevola approved these changes

2020-10-01 10:03 UTC, merged